eic/job_submission_condor

templates/osg_csv.submit.in

Updates project name used to submit jobs to OSG
Might not work for submissions from osgconnect (use of which is now discouraged anyways)

Update project name from EIC to ePIC

---

scripts/submit_csv.sh

Makes local log creation user-name agnostic.

Make local log creation user-name agnostic

---

templates/osg_csv.submit.in

Avoids getpass.getuser() exceptions
https://support.opensciencegrid.org/support/tickets/public/86e8fffbc59a5a8840189821d3141126a9d2a71753da5c592fbe64e270d592be
No
No

Use MappedUser option

---

templates/osg_csv.submit.in

Update undesired site list
No
No

Update undesired site list

---

templates/osg_csv.submit.in

Update unwanted site list

---

scripts/submit_csv.sh

This is now handled through xrdcp in the singles run script that fetches it from jlab xrootd

Don't transfer input files from S3 for singles

---

scripts/run_osg_test.sh

fix: dtn01 -> eics3

---

scripts/submit_csv.sh

Allow submission from custom csv input. This allows small scale testing with a subset of a dataset instead of using the full set.

Allow submission with custom csv input

---

templates/osg_csv.submit.in

Removes max materialize and idle job limits. This seems to help with achieving high raw throughput.

Remove max materialize and idle job limits

---

templates/osg_csv.submit.in

Update undesired sites and memory requirement (upped to 3.5 GB from 2.5 GB)

Update undesired sites and memory requirement

---

templates/osg_csv.submit.in

Use eic_xl image from cvmfs

---

templates/osg_csv.submit.in

Reimpose max idle limit of 500

Reimpose max idle limit of 500

---

templates/osg_csv.submit.in

Update requirements and undesired site list

Update requirements and undesired site list

---

templates/osg_csv.submit.in

Activate use_oauth_services for token issue and authentication

Activate use_oauth_services for token issue and authentication

---

scripts/csv_to_chunks.sh

Adjustment to read the extra fields but don't write them out to the csv file passed to condor
https://eicweb.phy.anl.gov/EIC/campaigns/datasets/-/commit/bdc1b4f48aef31d698f848723457f5ac331134de

Read extra fields but don't write them out to the csv file passed to condor

---

templates/osg_csv.submit.in

Update memory request and undesired sites

Update memory request and undesired sites

---

scripts/run.sh
scripts/submit_csv.sh

Use file extension to determine whether to stream or copy input because that's the only difference between hepmc3 and singles files

Feature merge hepmc3 and singles submission

---

scripts/submit_csv.sh

Extract certificate base name before adding it to environment

Extract certificate base name before adding it to environment

---

templates/osg_csv.submit.in

Update list of blacklisted sites

Update list of blacklisted sites

---

templates/osg_csv.submit.in

Lift memory upper limit to 3G because it seems like most jobs are requiring more than the current limit of 2.5

Lift memory upper limit to 3G

---

scripts/submit_csv.sh

Prevent duplication of environment setting script naming in successive submits

Prevent duplication of environment setting script naming in successive submits
